apiVersion: v1
kind: Service
metadata:
  name: pf9-redis
  namespace: {{ include "pf9mngt.namespace" . }}
  labels:
    {{- include "pf9mngt.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    {{- include "pf9mngt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - port: {{ .Values.redisService.service.port }}
      targetPort: 6379
      protocol: TCP
      name: redis
