apiVersion: v1
kind: Service
metadata:
  name: pf9-monitoring
  namespace: {{ include "pf9mngt.namespace" . }}
  labels:
    {{- include "pf9mngt.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
spec:
  type: {{ .Values.monitoring.service.type }}
  selector:
    {{- include "pf9mngt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
  ports:
    - port: {{ .Values.monitoring.service.port }}
      targetPort: 8001
      protocol: TCP
      name: http
