apiVersion: v1
kind: Service
metadata:
  name: pf9-pgbouncer
  namespace: {{ include "pf9mngt.namespace" . }}
  labels:
    {{- include "pf9mngt.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgbouncer
spec:
  type: ClusterIP
  selector:
    {{- include "pf9mngt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: pgbouncer
  ports:
    - name: pgbouncer
      port: 5432
      targetPort: 5432
      protocol: TCP
