#!/bin/sh
# ---------------------------------------------------------------------------
# PgBouncer entrypoint — generate pgbouncer.ini + userlist.txt from env vars,
# then exec pgbouncer so it replaces this shell process (PID 1 behaviour).
#
# Required env vars:
#   PGBOUNCER_DB_HOST         PostgreSQL host
#   PGBOUNCER_DB_PORT         PostgreSQL port (default: 5432)
#   PGBOUNCER_AUTH_USER       DB superuser pgbouncer uses for auth_query
#   PGBOUNCER_AUTH_PASSWORD   cleartext password for that user
#   PGBOUNCER_POOL_SIZE       default_pool_size (default: 20)
#   PGBOUNCER_MAX_CLIENT_CONN max_client_conn (default: 200)
# ---------------------------------------------------------------------------
set -eu

: "${PGBOUNCER_DB_HOST:?ERROR: PGBOUNCER_DB_HOST must be set}"
: "${PGBOUNCER_AUTH_USER:?ERROR: PGBOUNCER_AUTH_USER must be set}"
: "${PGBOUNCER_AUTH_PASSWORD:?ERROR: PGBOUNCER_AUTH_PASSWORD must be set}"

PGBOUNCER_DB_PORT="${PGBOUNCER_DB_PORT:-5432}"
PGBOUNCER_POOL_SIZE="${PGBOUNCER_POOL_SIZE:-20}"
PGBOUNCER_MAX_CLIENT_CONN="${PGBOUNCER_MAX_CLIENT_CONN:-200}"

INI="/etc/pgbouncer/pgbouncer.ini"
USERLIST="/etc/pgbouncer/userlist.txt"

# Generate pgbouncer.ini from env vars
cat > "${INI}" << PGBOUNCER_EOF
; PgBouncer configuration -- auto-generated by entrypoint.sh
[databases]
* = host=${PGBOUNCER_DB_HOST} port=${PGBOUNCER_DB_PORT}

[pgbouncer]
listen_addr         = 0.0.0.0
listen_port         = 5432

auth_type           = scram-sha-256
auth_file           = ${USERLIST}
auth_user           = ${PGBOUNCER_AUTH_USER}
auth_query          = SELECT usename, passwd FROM pg_shadow WHERE usename=\$1

pool_mode           = transaction
default_pool_size   = ${PGBOUNCER_POOL_SIZE}
max_client_conn     = ${PGBOUNCER_MAX_CLIENT_CONN}

ignore_startup_parameters = extra_float_digits
server_reset_query  = DISCARD ALL

log_connections     = 0
log_disconnections  = 0
log_pooler_errors   = 1
stats_period        = 60
PGBOUNCER_EOF

chmod 600 "${INI}"

# Generate userlist.txt
printf '"%s" "%s"\n' "${PGBOUNCER_AUTH_USER}" "${PGBOUNCER_AUTH_PASSWORD}" > "${USERLIST}"
chmod 600 "${USERLIST}"

exec /opt/pgbouncer/pgbouncer "${INI}" "$@"