ALTER TABLE servers ADD COLUMN IF NOT EXISTS image_id TEXT;
ALTER TABLE servers ADD COLUMN IF NOT EXISTS os_distro TEXT;
ALTER TABLE servers ADD COLUMN IF NOT EXISTS os_version TEXT;
ALTER TABLE hypervisors ADD COLUMN IF NOT EXISTS running_vms INTEGER DEFAULT 0;
ALTER TABLE hypervisors ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
