apiVersion: v1
kind: Service
metadata:
  name: pf9-tenant-portal
  namespace: {{ include "pf9mngt.namespace" . }}
  labels:
    {{- include "pf9mngt.labels" . | nindent 4 }}
    app.kubernetes.io/component: tenant-portal
spec:
  type: {{ .Values.tenantPortal.service.type }}
  selector:
    {{- include "pf9mngt.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: tenant-portal
  ports:
    - port: {{ .Values.tenantPortal.service.port }}
      targetPort: 8010
      protocol: TCP
      name: http
